package com.google.model;

import java.math.BigDecimal;
import java.util.Date;

public class FruitShopOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit_shop_order.id
     *
     * @mbg.generated Wed Jun 30 14:51:57 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit_shop_order.stuId
     *
     * @mbg.generated Wed Jun 30 14:51:57 CST 2021
     */
    private Long stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit_shop_order.price
     *
     * @mbg.generated Wed Jun 30 14:51:57 CST 2021
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit_shop_order.datetime
     *
     * @mbg.generated Wed Jun 30 14:51:57 CST 2021
     */
    private Date datetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit_shop_order.id
     *
     * @return the value of fruit_shop_order.id
     *
     * @mbg.generated Wed Jun 30 14:51:57 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruit_shop_order.id
     *
     * @param id the value for fruit_shop_order.id
     *
     * @mbg.generated Wed Jun 30 14:51:57 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit_shop_order.stuId
     *
     * @return the value of fruit_shop_order.stuId
     *
     * @mbg.generated Wed Jun 30 14:51:57 CST 2021
     */
    public Long getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruit_shop_order.stuId
     *
     * @param stuid the value for fruit_shop_order.stuId
     *
     * @mbg.generated Wed Jun 30 14:51:57 CST 2021
     */
    public void setStuid(Long stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit_shop_order.price
     *
     * @return the value of fruit_shop_order.price
     *
     * @mbg.generated Wed Jun 30 14:51:57 CST 2021
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruit_shop_order.price
     *
     * @param price the value for fruit_shop_order.price
     *
     * @mbg.generated Wed Jun 30 14:51:57 CST 2021
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit_shop_order.datetime
     *
     * @return the value of fruit_shop_order.datetime
     *
     * @mbg.generated Wed Jun 30 14:51:57 CST 2021
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruit_shop_order.datetime
     *
     * @param datetime the value for fruit_shop_order.datetime
     *
     * @mbg.generated Wed Jun 30 14:51:57 CST 2021
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    @Override
    public String toString() {
        return "FruitShopOrder{" +
                "id=" + id +
                ", stuid=" + stuid +
                ", price=" + price +
                ", datetime=" + datetime +
                '}';
    }
}